### ISSUE TITLE
Schematic Diagram

### ISSUE THREAD

**Issue by mikeshams** [simranflora28/CAPSTONE_EMBT_WINTER2020#3]
Discuss DRC in the context of schematic design here!

**Comment by simranflora28** [comment]
As we are using EASYEDA software for schematic design. So, there is no option for DRC(design rule checking) while making a schematic because a schematic is just a rough drawing for the actual project. 

DRC will be there on the board designing like we will do the PCB design it's available in the DESIGN menu.

Design Rule Checking (DRC) is a process used to identify errors and mismatches such as spacing & trace widths in a PCB design/layout. The layout of a PCB board is designed using software, each PCB fabricator has a set of rules which they publish that specify various parameters such as what the spacing between each line should be, the minimum size of vias, the width of a line, etc.
