### ISSUE TITLE
Integrating Codes

### ISSUE THREAD

**Issue by mikeshams** [simranflora28/CAPSTONE_EMBT_WINTER2020#9]
How did you integrate your code? Explain step by step here with your references!

**Comment by simranflora28** [comment]
Integration of codes means combining two different codes for two different components together. To elucidate, we are using a fingerprint sensor with Arduino mega and at the same time, we are using a gsm module. so, for the final, we are combining these two different codes together.
main steps are:
open the two different codes in Arduino ide
merge the smaller code within the bigger one.
copy the required parameters as per the required functions, and don't forget to combine the libraries.
after making any changes compile the code first, to check the error.
Testing the components before integrating is necessary.
Make sure in the integrated code there should be only one void setup() function and one void loop() function.
we can use the looping statements in the void loop() function in order to obtain the required output.
once the code is complied properly, execute it and upload it to the board.
References: https://www.youtube.com/watch?v=mFprp4UCx1g; https://www.quora.com/How-do-I-upload-two-different-codes-of-a-sensor-in-a-single-Arduino-board
